/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;


import dados.JogadoresModelo;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.JogadorNegocio;

/**
 *
 * @author Gustavo
 */
public class TelaCadastro extends javax.swing.JDialog {
    private JogadoresModelo referenciaJogadores;
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro(JogadorNegocio cadastroJogadores,java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.referenciaJogadores = new JogadoresModelo();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTF_nome = new javax.swing.JTextField();
        jB_cancelar = new javax.swing.JButton();
        jB_Salvar = new javax.swing.JButton();
        jB_primeiro = new javax.swing.JButton();
        jB_anterior = new javax.swing.JButton();
        jB_proximo = new javax.swing.JButton();
        jB_ultimo = new javax.swing.JButton();
        jB_Novo = new javax.swing.JButton();
        jB_Alterar = new javax.swing.JButton();
        jB_Excluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTF_Id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCB_titular = new javax.swing.JComboBox<>();
        jTF_posicao = new javax.swing.JTextField();
        jTF_numerocamisa = new javax.swing.JTextField();
        jTF_numerogol = new javax.swing.JTextField();
        jTF_idade = new javax.swing.JTextField();
        jTF_time = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTF_Pesquisa = new javax.swing.JTextField();
        jB_pesquisa = new javax.swing.JButton();
        jB_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome");

        jB_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cancel_24x24.png"))); // NOI18N
        jB_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarActionPerformed(evt);
            }
        });

        jB_Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save_24x24.png"))); // NOI18N
        jB_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SalvarActionPerformed(evt);
            }
        });

        jB_primeiro.setText("Primeiro");
        jB_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_primeiroActionPerformed(evt);
            }
        });

        jB_anterior.setText("Anterior");
        jB_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_anteriorActionPerformed(evt);
            }
        });

        jB_proximo.setText("Próximo");
        jB_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_proximoActionPerformed(evt);
            }
        });

        jB_ultimo.setText("Último");
        jB_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ultimoActionPerformed(evt);
            }
        });

        jB_Novo.setText("Novo");
        jB_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_NovoActionPerformed(evt);
            }
        });

        jB_Alterar.setText("Alterar");
        jB_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AlterarActionPerformed(evt);
            }
        });

        jB_Excluir.setText("Excluir");
        jB_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ExcluirActionPerformed(evt);
            }
        });

        jLabel5.setText("Índice");

        jLabel2.setText("Time");

        jLabel3.setText("Idade");

        jLabel4.setText("Número de gols");

        jLabel6.setText("Número da Camisa");

        jLabel7.setText("Posição");

        jLabel8.setText("Titular");

        jCB_titular.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        jCB_titular.setSelectedIndex(1);
        jCB_titular.setToolTipText("");

        jLabel9.setText("Pesquise o id do jogador:");

        jTF_Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_PesquisaActionPerformed(evt);
            }
        });

        jB_pesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Preview_16x16.png"))); // NOI18N
        jB_pesquisa.setText("pesquisar");
        jB_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_pesquisaActionPerformed(evt);
            }
        });

        jB_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Undo_24x24.png"))); // NOI18N
        jB_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_primeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB_proximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_ultimo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jB_pesquisa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF_posicao, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addGap(50, 50, 50))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(7, 7, 7)
                                                .addComponent(jTF_Id))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTF_time)
                                                    .addComponent(jTF_nome))))
                                        .addGap(58, 58, 58)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(75, 75, 75)
                                        .addComponent(jCB_titular, 0, 82, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(79, 79, 79)
                                        .addComponent(jTF_idade))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF_numerocamisa))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(23, 23, 23)
                                        .addComponent(jTF_numerogol)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(88, 88, 88)
                                            .addComponent(jB_Novo))
                                        .addComponent(jB_Alterar, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(jB_Excluir))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jB_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jB_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jB_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jB_Salvar, jB_cancelar, jB_voltar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTF_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_pesquisa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_primeiro)
                    .addComponent(jB_anterior)
                    .addComponent(jB_proximo)
                    .addComponent(jB_ultimo))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_Id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jB_Novo)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3)
                        .addComponent(jTF_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Alterar)
                    .addComponent(jLabel2)
                    .addComponent(jTF_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTF_numerogol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Excluir)
                    .addComponent(jTF_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jTF_numerocamisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTF_posicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jCB_titular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jB_cancelar)
                        .addComponent(jB_Salvar))
                    .addComponent(jB_voltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTF_idade, jTF_numerocamisa, jTF_numerogol});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jB_Salvar, jB_cancelar, jB_voltar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SalvarActionPerformed
        // TODO add your handling code here:
       JogadorNegocio jogadorNegocio = new JogadorNegocio();
        try {
            jogadorNegocio.inserirJogadores(jTF_time.getText(),jTF_nome.getText(),Integer.parseInt(jTF_idade.getText()), Integer.parseInt(jTF_numerogol.getText()),Integer.parseInt(jTF_numerocamisa.getText()),jTF_posicao.getText(),jCB_titular.getSelectedIndex());
            
            
//cadastroProdutoNegocio.solicitarGravacaoProdutos(jTF_nomeProduto.getText(), jTextArea1.getText(), jTF_precoCompra.getText(), jCB_disponibilidadedevenda.getSelectedIndex());
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_SalvarActionPerformed

    private void jB_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarActionPerformed
        // TODO add your handling code here:
        jTF_Id.setText(null);
        jTF_Id.setEditable(false);
        jTF_nome.setText(null);
        jTF_time.setText(null);
        jTF_posicao.setText(null);
        jTF_idade.setText("0");
        jTF_numerocamisa.setText("0");
        jTF_numerogol.setText("0");
        jTF_nome.requestFocus();
        //this.dispose();
    }//GEN-LAST:event_jB_cancelarActionPerformed

    private void jB_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_NovoActionPerformed
        // TODO add your handling code here:
        jTF_Id.setText(null);
        jTF_Id.setEditable(false);
        jTF_nome.setText(null);
        jTF_time.setText(null);
        jTF_posicao.setText(null);
        jTF_idade.setText("0");
        jTF_numerocamisa.setText("0");
        jTF_numerogol.setText("0");
        jTF_nome.requestFocus();
            
    }//GEN-LAST:event_jB_NovoActionPerformed

    private void jB_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AlterarActionPerformed
        // TODO add your handling code here:
        
        JogadorNegocio jogadoresNegocio = new JogadorNegocio();
        try {
            jogadoresNegocio.alterarJogadores(jTF_Id.getText(),jTF_time.getText(),jTF_nome.getText(),Integer.parseInt(jTF_idade.getText()),Integer.parseInt(jTF_numerogol.getText()),Integer.parseInt(jTF_numerocamisa.getText()),jTF_posicao.getText(),jCB_titular.getSelectedIndex());
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_AlterarActionPerformed

    private void jB_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ExcluirActionPerformed
        // TODO add your handling code here:
        JogadorNegocio jogadoresNegocio = new JogadorNegocio();
        
        try {
            jogadoresNegocio.removerJogadores(jTF_Id.getText());
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jB_ExcluirActionPerformed

    private void jB_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_primeiroActionPerformed
        // TODO add your handling code here:
        JogadorNegocio jogadoresNegocio = new JogadorNegocio();
        try {
            jogadoresNegocio.localizaPrimeiroJogador(referenciaJogadores);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTF_Id.setText(String.valueOf(referenciaJogadores.getId()));
        jTF_Id.setEditable(false);
        jTF_nome.setText(referenciaJogadores.getNome());
        jTF_time.setText(referenciaJogadores.getTime());
        jTF_posicao.setText(referenciaJogadores.getPosicao());
        jTF_idade.setText(String.valueOf(referenciaJogadores.getIdade()));
        jTF_numerocamisa.setText(String.valueOf(referenciaJogadores.getNumerocamisa()));
        jTF_numerogol.setText(String.valueOf(referenciaJogadores.getNumerodegols()));
        jCB_titular.setSelectedIndex(referenciaJogadores.getTitular());
        jTF_nome.requestFocus();
    }//GEN-LAST:event_jB_primeiroActionPerformed

    private void jB_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_proximoActionPerformed
        // TODO add your handling code here:
        JogadorNegocio jogadoresNegocio = new JogadorNegocio();
        
        try {
            jogadoresNegocio.localizaProximoJogador(referenciaJogadores,jTF_Id.getText());
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTF_Id.setText(String.valueOf(referenciaJogadores.getId()));
        jTF_Id.setEditable(false);
        jTF_nome.setText(referenciaJogadores.getNome());
        jTF_time.setText(referenciaJogadores.getTime());
        jTF_posicao.setText(referenciaJogadores.getPosicao());
        jTF_idade.setText(String.valueOf(referenciaJogadores.getIdade()));
        jTF_numerocamisa.setText(String.valueOf(referenciaJogadores.getNumerocamisa()));
        jTF_numerogol.setText(String.valueOf(referenciaJogadores.getNumerodegols()));
        jCB_titular.setSelectedIndex(referenciaJogadores.getTitular());
        jTF_nome.requestFocus();
    }//GEN-LAST:event_jB_proximoActionPerformed

    private void jB_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ultimoActionPerformed
        // TODO add your handling code here:
        
        JogadorNegocio jogadoresNegocio = new JogadorNegocio();
        
        try {
            jogadoresNegocio.localizaUltimoJogador(referenciaJogadores);
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTF_Id.setText(String.valueOf(referenciaJogadores.getId()));
        jTF_Id.setEditable(false);
        jTF_nome.setText(referenciaJogadores.getNome());
        jTF_time.setText(referenciaJogadores.getTime());
        jTF_posicao.setText(referenciaJogadores.getPosicao());
        jTF_idade.setText(String.valueOf(referenciaJogadores.getIdade()));
        jTF_numerocamisa.setText(String.valueOf(referenciaJogadores.getNumerocamisa()));
        jTF_numerogol.setText(String.valueOf(referenciaJogadores.getNumerodegols()));
        jCB_titular.setSelectedIndex(referenciaJogadores.getTitular());
        jTF_nome.requestFocus();
        
    }//GEN-LAST:event_jB_ultimoActionPerformed

    private void jB_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_anteriorActionPerformed
        // TODO add your handling code here:
        JogadorNegocio jogadoresNegocio = new JogadorNegocio();
        
        try {
            jogadoresNegocio.localizaJogadorAnterior(referenciaJogadores,jTF_Id.getText());
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTF_Id.setText(String.valueOf(referenciaJogadores.getId()));
        jTF_Id.setEditable(false);
        jTF_nome.setText(referenciaJogadores.getNome());
        jTF_time.setText(referenciaJogadores.getTime());
        jTF_posicao.setText(referenciaJogadores.getPosicao());
        jTF_idade.setText(String.valueOf(referenciaJogadores.getIdade()));
        jTF_numerocamisa.setText(String.valueOf(referenciaJogadores.getNumerocamisa()));
        jTF_numerogol.setText(String.valueOf(referenciaJogadores.getNumerodegols()));
        jCB_titular.setSelectedIndex(referenciaJogadores.getTitular());
        jTF_nome.requestFocus();
    }//GEN-LAST:event_jB_anteriorActionPerformed

    private void jTF_PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_PesquisaActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jTF_PesquisaActionPerformed

    private void jB_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_pesquisaActionPerformed
        // TODO add your handling code here:
        
        JogadorNegocio jogadoresNegocio = new JogadorNegocio();
        
        try {
            jogadoresNegocio.localizaJogadorCadastro(referenciaJogadores,jTF_Pesquisa.getText());
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jTF_Id.setText(String.valueOf(referenciaJogadores.getId()));
        jTF_Id.setEditable(false);
        jTF_nome.setText(referenciaJogadores.getNome());
        jTF_time.setText(referenciaJogadores.getTime());
        jTF_posicao.setText(referenciaJogadores.getPosicao());
        jTF_idade.setText(String.valueOf(referenciaJogadores.getIdade()));
        jTF_numerocamisa.setText(String.valueOf(referenciaJogadores.getNumerocamisa()));
        jTF_numerogol.setText(String.valueOf(referenciaJogadores.getNumerodegols()));
        jCB_titular.setSelectedIndex(referenciaJogadores.getTitular());
        jTF_nome.requestFocus();
        
    }//GEN-LAST:event_jB_pesquisaActionPerformed

    private void jB_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_voltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jB_voltarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                TelaCadastro dialog = new TelaCadastro(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Alterar;
    private javax.swing.JButton jB_Excluir;
    private javax.swing.JButton jB_Novo;
    private javax.swing.JButton jB_Salvar;
    private javax.swing.JButton jB_anterior;
    private javax.swing.JButton jB_cancelar;
    private javax.swing.JButton jB_pesquisa;
    private javax.swing.JButton jB_primeiro;
    private javax.swing.JButton jB_proximo;
    private javax.swing.JButton jB_ultimo;
    private javax.swing.JButton jB_voltar;
    private javax.swing.JComboBox<String> jCB_titular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTF_Id;
    private javax.swing.JTextField jTF_Pesquisa;
    private javax.swing.JTextField jTF_idade;
    private javax.swing.JTextField jTF_nome;
    private javax.swing.JTextField jTF_numerocamisa;
    private javax.swing.JTextField jTF_numerogol;
    private javax.swing.JTextField jTF_posicao;
    private javax.swing.JTextField jTF_time;
    // End of variables declaration//GEN-END:variables
}
