/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import dados.ProdutoModelo;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import negocio.ProdutoNegocio;

/**
 *
 * @author Gustavo
 */
public class TelaVizualizaCadastro extends javax.swing.JDialog {
    private ProdutoNegocio produtoNegocio;
    /**
     * Creates new form TelaVizualizaCadastro
     */
    public TelaVizualizaCadastro(ProdutoNegocio produtoNegocio,java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.produtoNegocio=produtoNegocio;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jB_Voltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_vizualizaProduto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jB_Pesquisar = new javax.swing.JButton();
        jTF_Pesquisar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jToolBar1.setRollover(true);

        jB_Voltar.setText("Voltar");
        jB_Voltar.setFocusable(false);
        jB_Voltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jB_Voltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jB_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_VoltarActionPerformed(evt);
            }
        });
        jToolBar1.add(jB_Voltar);

        jT_vizualizaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jT_vizualizaProduto);

        jLabel1.setText("Digite o nome do produto a ser pesquisado");

        jB_Pesquisar.setText("Pesquisar");
        jB_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_PesquisarActionPerformed(evt);
            }
        });

        jTF_Pesquisar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTF_PesquisarCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTF_Pesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(jB_Pesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Pesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_VoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jB_VoltarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
//        ArrayList<ProdutoModelo> dados = produtoNegocio.getDadosGravados();
//        String [] nomesColunas = {"Nome Produto", "Preço Custo", "Preço Venda", "habilitado p/ Venda"};
//        String[][] valoresLinhas = new String[dados.size()][4];
//        
//        for(int i=0;i<dados.size();i++){
//            valoresLinhas[i][0] = dados.get(i).getNomeProduto();
//            valoresLinhas[i][1] = String.valueOf(dados.get(i).getPrecoCusto());
//            valoresLinhas[i][2] = String.valueOf(dados.get(i).getPrecoVenda());
//            valoresLinhas[i][3] = String.valueOf(dados.get(i).getHabilitarVenda());
//        }
//        DefaultTableModel tableModel = new DefaultTableModel(valoresLinhas,nomesColunas);
//        this.jTable1.setModel(tableModel);
        PesquisaParaTabela();
    }//GEN-LAST:event_formWindowActivated

    private void jB_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_PesquisarActionPerformed
        PesquisaParaTabela();
    }//GEN-LAST:event_jB_PesquisarActionPerformed

    private void PesquisaParaTabela() {
        // TODO add your handling code here:
        String [] nomesColunas = {"ID", "Nome Produto", "Especificacao Tecnica","Preco Custo","Preco Venda", "habilitado p/ Venda"};
        
        ProdutoNegocio produtoNegocio = new ProdutoNegocio();
        
        ArrayList<ProdutoModelo> dados = null;
        
        try {
            dados = produtoNegocio.consultarProdutos("%" + jTF_Pesquisar.getText() + "%");
        } catch (SQLException ex) {
            Logger.getLogger(TelaVizualizaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String[][] valoresLinhas = new String[dados.size()][6];
//
for(int i=0;i<dados.size();i++){
    valoresLinhas[i][0] = String.valueOf(dados.get(i).getId());
    valoresLinhas[i][1] = String.valueOf(dados.get(i).getNomeProduto());
    valoresLinhas[i][2] = String.valueOf(dados.get(i).getEspecificacaoTecnica());
    valoresLinhas[i][3] = String.valueOf(dados.get(i).getPrecoCusto());
    valoresLinhas[i][4] = String.valueOf(dados.get(i).getPrecoVenda());
    valoresLinhas[i][5] = String.valueOf(dados.get(i).getHabilitarVenda());
}
DefaultTableModel tableModel = new DefaultTableModel(valoresLinhas,nomesColunas);
this.jT_vizualizaProduto.setModel(tableModel);
    }

    private void jTF_PesquisarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTF_PesquisarCaretUpdate
        // TODO add your handling code here:
        PesquisaParaTabela();
//
    }//GEN-LAST:event_jTF_PesquisarCaretUpdate

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaVizualizaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaVizualizaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaVizualizaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaVizualizaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                TelaVizualizaCadastro dialog = new TelaVizualizaCadastro(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Pesquisar;
    private javax.swing.JButton jB_Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_Pesquisar;
    private javax.swing.JTable jT_vizualizaProduto;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
