/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gustavo
 */
public class NewJFrame extends javax.swing.JFrame {
   
    double numero1, numero2, resultado;
    char operacao;
    String temp;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_back = new javax.swing.JButton();
        jB_7 = new javax.swing.JButton();
        jB_4 = new javax.swing.JButton();
        jB_1 = new javax.swing.JButton();
        jB_0 = new javax.swing.JButton();
        jB_CE = new javax.swing.JButton();
        jB_8 = new javax.swing.JButton();
        jB_5 = new javax.swing.JButton();
        jB_2 = new javax.swing.JButton();
        jB_ponto = new javax.swing.JButton();
        jB_backspace = new javax.swing.JButton();
        jB_9 = new javax.swing.JButton();
        jB_6 = new javax.swing.JButton();
        jB_3 = new javax.swing.JButton();
        jB_igual = new javax.swing.JButton();
        jB_sinal = new javax.swing.JButton();
        jB_divisao = new javax.swing.JButton();
        jB_multiplicacao = new javax.swing.JButton();
        jB_subtracao = new javax.swing.JButton();
        jB_soma = new javax.swing.JButton();
        jTF_Visor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jB_back.setText("Back");
        jB_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_backActionPerformed(evt);
            }
        });

        jB_7.setText("7");
        jB_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_7ActionPerformed(evt);
            }
        });

        jB_4.setText("4");
        jB_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_4ActionPerformed(evt);
            }
        });

        jB_1.setText("1");
        jB_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_1ActionPerformed(evt);
            }
        });

        jB_0.setText("0");
        jB_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_0ActionPerformed(evt);
            }
        });

        jB_CE.setText("CE");
        jB_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_CEActionPerformed(evt);
            }
        });

        jB_8.setText("8");
        jB_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_8ActionPerformed(evt);
            }
        });

        jB_5.setText("5");
        jB_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_5ActionPerformed(evt);
            }
        });

        jB_2.setText("2");
        jB_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_2ActionPerformed(evt);
            }
        });

        jB_ponto.setText(".");
        jB_ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_pontoActionPerformed(evt);
            }
        });

        jB_backspace.setText("C");
        jB_backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_backspaceActionPerformed(evt);
            }
        });

        jB_9.setText("9");
        jB_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_9ActionPerformed(evt);
            }
        });

        jB_6.setText("6");
        jB_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_6ActionPerformed(evt);
            }
        });

        jB_3.setText("3");
        jB_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_3ActionPerformed(evt);
            }
        });

        jB_igual.setText("=");
        jB_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_igualActionPerformed(evt);
            }
        });

        jB_sinal.setText("+/-");
        jB_sinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_sinalActionPerformed(evt);
            }
        });

        jB_divisao.setText("/");
        jB_divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_divisaoActionPerformed(evt);
            }
        });

        jB_multiplicacao.setText("*");
        jB_multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_multiplicacaoActionPerformed(evt);
            }
        });

        jB_subtracao.setText("-");
        jB_subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_subtracaoActionPerformed(evt);
            }
        });

        jB_soma.setText("+");
        jB_soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_somaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTF_Visor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jB_0, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                .addComponent(jB_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jB_2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                .addComponent(jB_ponto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jB_igual, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                .addComponent(jB_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(6, 6, 6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jB_subtracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB_soma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jB_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(jB_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jB_backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jB_8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                        .addComponent(jB_5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jB_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jB_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jB_sinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB_divisao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB_multiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jB_0, jB_1, jB_2, jB_3, jB_4, jB_5, jB_6, jB_7, jB_8, jB_9, jB_CE, jB_back, jB_backspace, jB_divisao, jB_igual, jB_multiplicacao, jB_ponto, jB_sinal, jB_soma, jB_subtracao});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTF_Visor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_back)
                    .addComponent(jB_CE)
                    .addComponent(jB_backspace)
                    .addComponent(jB_sinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_7)
                    .addComponent(jB_8)
                    .addComponent(jB_9)
                    .addComponent(jB_divisao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_4)
                    .addComponent(jB_5)
                    .addComponent(jB_6)
                    .addComponent(jB_multiplicacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_1)
                    .addComponent(jB_2)
                    .addComponent(jB_3)
                    .addComponent(jB_subtracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_0)
                    .addComponent(jB_ponto)
                    .addComponent(jB_igual)
                    .addComponent(jB_soma))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_7ActionPerformed
        // TODO add your handling code here:
        getNumeroDigitado("7");
        
    }//GEN-LAST:event_jB_7ActionPerformed

    private void jB_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_1ActionPerformed
        // TODO add your handling code here:
        getNumeroDigitado("1");
    }//GEN-LAST:event_jB_1ActionPerformed

    private void jB_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_5ActionPerformed
        // TODO add your handling code here:
        getNumeroDigitado("5");
    }//GEN-LAST:event_jB_5ActionPerformed

    private void jB_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_0ActionPerformed
        // TODO add your handling code here:
        getNumeroDigitado("0");
    }//GEN-LAST:event_jB_0ActionPerformed

    private void jB_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_4ActionPerformed
        getNumeroDigitado("4");
    }//GEN-LAST:event_jB_4ActionPerformed

    private void jB_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_8ActionPerformed
        // TODO add your handling code here:
        getNumeroDigitado("8");
    }//GEN-LAST:event_jB_8ActionPerformed

    private void jB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_2ActionPerformed
        // TODO add your handling code here:
        getNumeroDigitado("2");
    }//GEN-LAST:event_jB_2ActionPerformed

    private void jB_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_9ActionPerformed
        // TODO add your handling code here:
        getNumeroDigitado("9");
    }//GEN-LAST:event_jB_9ActionPerformed

    private void jB_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_6ActionPerformed
        // TODO add your handling code here:
        getNumeroDigitado("6");
        
    }//GEN-LAST:event_jB_6ActionPerformed

    private void jB_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_3ActionPerformed
        // TODO add your handling code here:
        getNumeroDigitado("3");
    }//GEN-LAST:event_jB_3ActionPerformed

    private void jB_somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_somaActionPerformed
        Operacao('+');
    }//GEN-LAST:event_jB_somaActionPerformed

    private void Operacao(char op) throws NumberFormatException {
        // TODO add your handling code here:
        operacao=op;
        numero1=Double.parseDouble(jTF_Visor.getText());
        jTF_Visor.setText("");
    }

    private void jB_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_igualActionPerformed
        // TODO add your handling code here:
        numero2=Double.parseDouble(jTF_Visor.getText());
        switch(operacao){
            case '+':
                    resultado = numero1+numero2;
                    break;
            case '-':
                    resultado = numero1-numero2;
                    break;
            case '*':
                    resultado = numero1*numero2;
                    break;
            case '/':
                    resultado = numero1/numero2;
                    break;
        }
        jTF_Visor.setText(String.valueOf(resultado));
    }//GEN-LAST:event_jB_igualActionPerformed

    private void jB_divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_divisaoActionPerformed
        // TODO add your handling code here:
        Operacao('/');
    }//GEN-LAST:event_jB_divisaoActionPerformed

    private void jB_multiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_multiplicacaoActionPerformed
        // TODO add your handling code here:
        Operacao('*');
    }//GEN-LAST:event_jB_multiplicacaoActionPerformed

    private void jB_subtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_subtracaoActionPerformed
        // TODO add your handling code here:
        Operacao('-');
    }//GEN-LAST:event_jB_subtracaoActionPerformed

    private void jB_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_CEActionPerformed
        // TODO add your handling code here:
        numero2 = 0;
        jTF_Visor.setText(String.valueOf(numero1));
    }//GEN-LAST:event_jB_CEActionPerformed

    private void jB_backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_backspaceActionPerformed
        // TODO add your handling code here:
        numero1=0;
        numero2=0;
        jTF_Visor.setText("");
    }//GEN-LAST:event_jB_backspaceActionPerformed

    private void jB_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_backActionPerformed
        // TODO add your handling code here:
        if(temp.isEmpty()){
            //temp = temp.substring(0, temp.length()-1);
        } else temp = temp.substring(0, temp.length()-1);
        jTF_Visor.setText(temp);
    }//GEN-LAST:event_jB_backActionPerformed

    private void jB_sinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_sinalActionPerformed
        // TODO add your handling code here:
        if(temp.startsWith("+")){
            temp=temp.replace("+", "-");
        }else if(temp.startsWith("-")){
            temp=temp.replace("-", "+");
        }else{
            temp="-"+temp;
        }
        jTF_Visor.setText(temp);
    }//GEN-LAST:event_jB_sinalActionPerformed

    private void jB_pontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_pontoActionPerformed
        // TODO add your handling code here:
        getNumeroDigitado(".");
    }//GEN-LAST:event_jB_pontoActionPerformed

    private void getNumeroDigitado(String num) {
        // TODO add your handling code here:
        temp = jTF_Visor.getText();
        temp = temp + num;
        jTF_Visor.setText(temp);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_0;
    private javax.swing.JButton jB_1;
    private javax.swing.JButton jB_2;
    private javax.swing.JButton jB_3;
    private javax.swing.JButton jB_4;
    private javax.swing.JButton jB_5;
    private javax.swing.JButton jB_6;
    private javax.swing.JButton jB_7;
    private javax.swing.JButton jB_8;
    private javax.swing.JButton jB_9;
    private javax.swing.JButton jB_CE;
    private javax.swing.JButton jB_back;
    private javax.swing.JButton jB_backspace;
    private javax.swing.JButton jB_divisao;
    private javax.swing.JButton jB_igual;
    private javax.swing.JButton jB_multiplicacao;
    private javax.swing.JButton jB_ponto;
    private javax.swing.JButton jB_sinal;
    private javax.swing.JButton jB_soma;
    private javax.swing.JButton jB_subtracao;
    private javax.swing.JTextField jTF_Visor;
    // End of variables declaration//GEN-END:variables
}
