/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gustavo
 */
public class GuiPrincipal extends javax.swing.JFrame {

    private Database dataBase = new Database();
    private GUIcadastroDVD dialogoCadastro = new GUIcadastroDVD(new java.awt.Frame(),true,dataBase);
    private GUICadastroCD dialogoCadastroCD = new GUICadastroCD(new java.awt.Frame(),true,dataBase);
    private GUIRelatorioDVD dialogoRelatorio = new GUIRelatorioDVD(new java.awt.Frame(),true,dataBase);
    private GuiRelatorioCD dialogoRelatorioCD = new GuiRelatorioCD(new java.awt.Frame(),true,dataBase);
    private GuiTelaSobre dialogoSobre = new GuiTelaSobre(this,true);
    /**
     * Creates new form GuiPrincipal
     */
    public GuiPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jM_Cadastro = new javax.swing.JMenu();
        jMI_cadastroDVD = new javax.swing.JMenuItem();
        jMI_cadastroCD = new javax.swing.JMenuItem();
        jM_relatorio = new javax.swing.JMenu();
        jM_relatorioDVD = new javax.swing.JMenuItem();
        jM_relatorioCD = new javax.swing.JMenuItem();
        jM_sobre = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jM_Cadastro.setText("Cadastro");

        jMI_cadastroDVD.setText("cadastro de dvd");
        jMI_cadastroDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_cadastroDVDActionPerformed(evt);
            }
        });
        jM_Cadastro.add(jMI_cadastroDVD);

        jMI_cadastroCD.setText("cadastro de cd");
        jMI_cadastroCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMI_cadastroCDActionPerformed(evt);
            }
        });
        jM_Cadastro.add(jMI_cadastroCD);

        jMenuBar1.add(jM_Cadastro);

        jM_relatorio.setText("Relatorio");

        jM_relatorioDVD.setText("relatorio de dvd");
        jM_relatorioDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_relatorioDVDActionPerformed(evt);
            }
        });
        jM_relatorio.add(jM_relatorioDVD);

        jM_relatorioCD.setText("relatorio de cd");
        jM_relatorioCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_relatorioCDActionPerformed(evt);
            }
        });
        jM_relatorio.add(jM_relatorioCD);

        jMenuBar1.add(jM_relatorio);

        jM_sobre.setText("Sobre");
        jM_sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_sobreActionPerformed(evt);
            }
        });

        jMenuItem1.setText("sobre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jM_sobre.add(jMenuItem1);

        jMenuBar1.add(jM_sobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jM_relatorioCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_relatorioCDActionPerformed
        // TODO add your handling code here:
        dialogoRelatorioCD.setVisible(true);
    }//GEN-LAST:event_jM_relatorioCDActionPerformed

    private void jMI_cadastroDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_cadastroDVDActionPerformed
        // TODO add your handling code here:
        dialogoCadastro.setVisible(true);
        
        
    }//GEN-LAST:event_jMI_cadastroDVDActionPerformed

    private void jM_relatorioDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_relatorioDVDActionPerformed
        // TODO add your handling code here:
        dialogoRelatorio.setVisible(true);
    }//GEN-LAST:event_jM_relatorioDVDActionPerformed

    private void jM_sobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_sobreActionPerformed
        // TODO add your handling code here:
        dialogoSobre.setVisible(true);
    }//GEN-LAST:event_jM_sobreActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dialogoSobre.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMI_cadastroCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMI_cadastroCDActionPerformed
        // TODO add your handling code here:
        dialogoCadastroCD.setVisible(true);
    }//GEN-LAST:event_jMI_cadastroCDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMI_cadastroCD;
    private javax.swing.JMenuItem jMI_cadastroDVD;
    private javax.swing.JMenu jM_Cadastro;
    private javax.swing.JMenu jM_relatorio;
    private javax.swing.JMenuItem jM_relatorioCD;
    private javax.swing.JMenuItem jM_relatorioDVD;
    private javax.swing.JMenu jM_sobre;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
